# 应用服务 WEB 访问端口
server:
  port: 8081

spring:
  mvc:
    contentnegotiation:
      favor-parameter: true # 使用参数进行内容协商（默认是没有开启的） ,默认参数名：format
      parameter-name: type # 修改内容协商的参数名称
  application:
    name: spring-boot-3-demo
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  data:
    redis:
      host: "localhost"
      port: 6379


# 猪
pig:
  id: 1
  name: 佩奇
  age: 5

# 羊
sheep:
  id: 1
  name: 苏西
  age: 5

#logging:
#  pattern:
#    console: "%d{yyy-MM-dd HH:mm:ss.sss}%-5level [%thread]%logger{15}===>%msg%n"
#  level:
#    root: debug
#  file:
#    name: D:/logs/springboot3.log

# 日志归档、切割
#  logback:
#    rollingpolicy:
#      file-name-pattern: "${LOG FILE}.%d{yyyy-MM-dd}.%i.gz"
#      max-file-size: 1MB
#      max-history: 7 # 日志保存7天

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '系统API'
      paths-to-match: '/**'
      #生成文档所需的扫包路径，一般为启动类目录
      packages-to-scan: com.example

#knife4j配置
knife4j:
  #是否启用增强设置
  enable: true
  #开启生产环境屏蔽
  production: false
  #是否启用登录认证
  basic:
    enable: true
    username: admin
    password: admin
  setting:
    language: zh_cn
    enable-version: true
    enable-swagger-models: true
#    swagger-model-name: 用户模块
