# 应用服务 WEB 访问端口
server:
  port: 8081
spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  data:
    redis:
      host: "localhost"
      port: 6379


# 猪
pig:
  id: 1
  name: 佩奇
  age: 5

# 羊
sheep:
  id: 1
  name: 苏西
  age: 5

#logging:
#  pattern:
#    console: "%d{yyy-MM-dd HH:mm:ss.sss}%-5level [%thread]%logger{15}===>%msg%n"
#  level:
#    root: debug
#  file:
#    name: D:/logs/springboot3.log

# 日志归档、切割
#  logback:
#    rollingpolicy:
#      file-name-pattern: "${LOG FILE}.%d{yyyy-MM-dd}.%i.gz"
#      max-file-size: 1MB
#      max-history: 7 # 日志保存7天

springdoc:
  swagger-ui:
   # 是否开启swagger界面，依赖OpenApi，默认为true，如果要开启需要OpenApi同时开启
     enabled: true
     # 内置 Swagger UI 的访问路径，默认值为/swagger-ui/index.html
     path: /swagger-ui/index.html
     # 指定OpenAPI文档的URL（注意这里一定要与api-docs.path保持一致，否则会请求失败）
     url: /v3/api-docs
     # 是否禁用Swagger UI自带的示例接口（如 Petstore 等默认接口），默认值为false，仅展示当前项目的 API
     disable-swagger-default-url: false
  api-docs:
   # 是否启用OpenAPI文档端点，默认为true
     enabled: true
     # OpenAPI 3规范的文档访问路径，默认值为/v3/api-docs
     path: /api-docs
