# 应用服务 WEB 访问端口
server:
  port: 8081
spring:
  thymeleaf:
    cache: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

  data:
    redis:
      host: "localhost"
      port: 6379


# 猪
pig:
  id: 1
  name: 佩奇
  age: 5

# 羊
sheep:
  id: 1
  name: 苏西
  age: 5

#logging:
#  pattern:
#    console: "%d{yyy-MM-dd HH:mm:ss.sss}%-5level [%thread]%logger{15}===>%msg%n"
#  level:
#    root: debug
#  file:
#    name: D:/logs/springboot3.log

# 日志归档、切割
#  logback:
#    rollingpolicy:
#      file-name-pattern: "${LOG FILE}.%d{yyyy-MM-dd}.%i.gz"
#      max-file-size: 1MB
#      max-history: 7 # 日志保存7天
